baseurl: http://nodejh.com/
languageCode: zh-cn
title: nodejh
theme: mini
googleAnalytics: UA-84989670-1
hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

disqusShortname: nodejh

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: 'https://www.github.com/nodejh'
  # twitter: 'https://www.twitter.com/nodejh'
  # stackoverflow: 'https://stackoverflow.com/users/4518882/nodejh'
  # facebook: 'https://www.facebook.com/nodejh'


# Site parameters
params:
  # Site Author
  author: nodejh
  # Author biography
  bio: Software Engineer
  # Site Description, used in HTML meat
  description: nodejh's blog
  enableRSS: true

  # Optional
  home: '' # Default: Home
  about: '' # Default: About
  archive: '' # Default: Archive
  subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: ''
  title404: '' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
